# Generated by Django 2.0.8 on 2021-07-29 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=100)),
                ('Manufacturing_date', models.DateField()),
                ('Net_Quantity', models.CharField(max_length=20)),
                ('Price', models.IntegerField()),
                ('TPrice', models.IntegerField(default=100)),
                ('Description', models.TextField(max_length=200)),
                ('Image', models.ImageField(upload_to='media/images')),
                ('Test_Status', models.CharField(max_length=100)),
                ('Availability', models.IntegerField()),
            ],
        ),
    ]
